CREATE TABLE IF NOT EXISTS Genres(
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(40) UNIQUE
);

CREATE TABLE IF NOT EXISTS Executors(
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Albums(
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(40) NOT NULL,
	"Year of issue" SERIAL CHECK("Year of issue" < 2023)
);

CREATE TABLE IF NOT EXISTS Tracks(
	ID INTEGER PRIMARY KEY REFERENCES Albums(ID),
	Name VARCHAR(40) NOT NULL,
	Duration TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Compilations(
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(40) NOT NULL,
	"Year of issue" SERIAL CHECK("Year of issue" < 2023)
);

CREATE TABLE IF NOT EXISTS GenresExecutors(
	ID SERIAL PRIMARY KEY,
	Genre_ID INTEGER NOT NULL REFERENCES Genres(ID),
	Executor_ID INTEGER NOT NULL REFERENCES Executors(ID)
);

CREATE TABLE IF NOT EXISTS ExecutorsAlbums(
	ID SERIAL PRIMARY KEY,
	Executor_ID INTEGER NOT NULL REFERENCES Executors(ID),
	Album_ID INTEGER NOT NULL REFERENCES Albums(ID)
);

CREATE TABLE IF NOT EXISTS TracksCompilations(
	ID SERIAL PRIMARY KEY,
	Track_ID INTEGER NOT NULL REFERENCES Tracks(ID),
	Compilation_ID INTEGER NOT NULL REFERENCES Compilations(ID)
);